#!/usr/bin/env bash
#
# Regenerate src/XMonad/River/Keysym.hs: X11-package values for the keysyms
# the Haskell X11 package exports, xkbcommon-keysym.h for the XF86 block it
# does not.
#
# Usage: util/gen-keysyms.sh
#
# Only needed when the set of keysyms changes, which in practice means bumping
# the X11 dependency.  The output is checked in.
#
# The values are read out of a real X11 build rather than transcribed, and that
# is the whole point: xkbcommon reuses X11's keysym numbering wholesale, so the
# numbers have to be *right*, and inventing 347 of them from memory is how you
# ship a config where one key silently stops working.  Reading them from the
# package that already has them makes the correspondence true by construction.
#
# The name list comes from upstream xmonad's recorded API, so a keysym upstream
# re-exports but this script missed would show up as a golden diff rather than
# as a key that mysteriously does nothing.

set -euo pipefail

cd "$(dirname "$0")/.."

out=src/XMonad/River/Keysym.hs
golden=tests/api/upstream/xmonad-reexports.golden

[ -f "$golden" ] || { echo "gen-keysyms: need $golden; record it with\n  tests/api/dump-api.sh tests/api/upstream ../xmonad" >&2; exit 1; }

tmp=$(mktemp -d)
trap 'rm -rf "$tmp"' EXIT

export LC_ALL=en_US.UTF-8

grep -E '^XMonad \| xK_' "$golden" | cut -d'|' -f2 | tr -d ' ' | sort -u > "$tmp/names"

# XF86 keysyms: the Haskell X11 package does not export these, so they
# cannot come out of the probe below.  xkbcommon publishes the same X11
# numbering in xkbcommon-keysyms.h; parse the #defines directly.  Names
# keep X11's spelling (no XKB_KEY_ prefix), as the table is keyed by it.
hdr=${XKBCOMMON_KEYSYM_HEADER:-}
if [ -z "$hdr" ]; then
  inc=$(pkg-config --variable=includedir libxkbcommon 2>/dev/null || true)
  [ -n "$inc" ] && [ -f "$inc/xkbcommon/xkbcommon-keysyms.h" ] \
    && hdr=$inc/xkbcommon/xkbcommon-keysyms.h
fi
if [ -z "$hdr" ] || [ ! -f "$hdr" ]; then
  echo "gen-keysyms: need xkbcommon-keysyms.h (set XKBCOMMON_KEYSYM_HEADER)" >&2
  exit 1
fi
# Lines: "xK_<name> 0x<value>".  Aliases (same value, another name) are kept;
# a name the X11 probe also produces wins below, the golden being the
# upstream-API truth.
grep -E '^#define XKB_KEY_XF86' "$hdr" \
  | awk '{ print "xK_" substr($2, 9), $3 }' | sort -u > "$tmp/xf86values"

{
    echo 'module Main (main) where'
    echo 'import Graphics.X11'
    echo 'main :: IO ()'
    echo 'main = do'
    sed 's/.*/  putStrLn ("&" ++ " " ++ show (toInteger &))/' "$tmp/names"
} > "$tmp/probe.hs"

stack exec --package X11 -- ghc -v0 -ignore-dot-ghci -o "$tmp/probe" "$tmp/probe.hs"
"$tmp/probe" > "$tmp/values"

python3 - "$tmp/values" "$tmp/xf86values" "$out" <<'PY'
import locale
import os
import sys
locale.setlocale(locale.LC_ALL, "")
# X11 probe values are decimal; xkbcommon header values are hex.  X11 wins
# on a name collision (see above), and a colliding name belongs to the X11
# surface, not the XF86 module.
value = {}
xf86_names = set()
for n, v in [l.split() for l in open(sys.argv[2])]:
    value[n] = int(v, 16)
    xf86_names.add(n)
x11_names = set()
for n, v in [l.split() for l in open(sys.argv[1])]:
    value[n] = int(v)
    x11_names.add(n)
names = sorted(value, key=locale.strxfrm)
vals = [(n, value[n]) for n in names]
# The X11 package's own names: XMonad.Core re-exports this module, so
# anything listed here enters xmonad's API surface and must have an X11
# counterpart (tests/api/check-subset.sh asserts exactly that).
vals_x11 = [(n, value[n]) for n in names if n in x11_names]
# Names only xkbcommon publishes (the whole XF86 block): river-specific,
# exported from XMonad.River.Keysym.XF86 -- which XMonad.Core does NOT
# re-export.  Configs written against upstream never see them; configs that
# want media keys import this module, or just use the "XF86AudioPlay"
# spelling with XMonad.Util.EZConfig, which goes through stringToKeysym and
# the shared table below.
vals_xf86 = [(n, value[n]) for n in names if n not in x11_names]

header = '''-- | Keysyms, with X11's values.
--
-- GENERATED by util/gen-keysyms.sh -- do not edit.
--
-- Not a compatibility shim.  xkbcommon reuses X11's keysym numbering
-- wholesale, and @river_xkb_bindings_v1.get_xkb_binding@ takes an xkbcommon
-- keysym directly, so @xK_Return@ is 0xff0d on both sides and a key
-- description means the same thing without translation.  That is one of the
-- two coincidences this port rests on; the other is that
-- @river_seat_v1.modifiers@ reuses X11's modifier mask values.
--
-- The values are read out of the X11 package rather than transcribed, because
-- inventing this many constants by hand is how you ship a config where one key
-- silently stops working.
module XMonad.River.Keysym (
  noSymbol, stringToKeysym, keysymToString,
%%NAMES%%
  ) where

import Data.Char (chr, ord)
import qualified Data.Map.Strict as M

import XMonad.River.Keysym.Table (keysymTable, reverseKeysymTable)
import XMonad.River.Types (KeySym)

-- | The keysym meaning "no key".  Zero, as XKB_KEY_NoSymbol is.
noSymbol :: KeySym
noSymbol = 0

-- | Parse a key name in X11\'s spelling, as "XMonad.Util.EZConfig" key
-- descriptions use.
--
-- Printable Latin-1 maps to its own code point, which is how X11 -- and
-- therefore xkbcommon -- numbers that range; everything else comes from the
-- table below.  Returns \'noSymbol\' for an unknown name, matching X11.
stringToKeysym :: String -> KeySym
stringToKeysym name = case M.lookup name keysymTable of
  Just ks -> ks
  Nothing -> case name of
    [c] | ord c >= 0x20 && ord c <= 0xff -> fromIntegral (ord c)
    _ -> noSymbol

-- | Inverse of \'stringToKeysym\'.
keysymToString :: KeySym -> String
keysymToString ks = case M.lookup ks reverseKeysymTable of
  Just name -> name
  Nothing
    | ks >= 0x20 && ks <= 0xff -> [chr (fromIntegral ks)]
    | otherwise -> "0x" ++ showHex ks
  where
    showHex 0 = "0"
    showHex n = go n ""
      where
        go 0 acc = acc
        go m acc = go (m `div` 16) (digit (m `mod` 16) : acc)
        digit d | d < 10 = chr (ord '0' + fromIntegral d)
                | otherwise = chr (ord 'a' + fromIntegral d - 10)

'''

names_block = []
for i in range(0, len(vals_x11), 6):
    chunk = ", ".join(n for n, _ in vals_x11[i:i + 6])
    names_block.append("  " + chunk + ("," if i + 6 < len(vals_x11) else ""))
header = header.replace("%%NAMES%%", "\n".join(names_block))

lines = [header]
# Continuation lines of a type signature must be indented, or they start a new
# declaration.
for i in range(0, len(vals_x11), 8):
    chunk = ", ".join(n for n, _ in vals_x11[i:i + 8])
    prefix = "" if i == 0 else "  "
    suffix = " :: KeySym" if i + 8 >= len(vals_x11) else ","
    lines.append(prefix + chunk + suffix)
lines.append("")
lines += [f"{n} = {v}" for n, v in vals_x11]

open(sys.argv[3], "w").write("\n".join(lines) + "\n")

# The XF86 block, as its own module: same values, same X11 spelling, but a
# river-specific home (see vals_xf86 above).
xf86_header = '''-- | The XF86 keysyms, with X11's values.
--
-- GENERATED by util/gen-keysyms.sh -- do not edit.
--
-- The Haskell X11 package does not export these, so they are not part of
-- xmonad's upstream-shaped API surface; "XMonad.Core" does not re-export
-- this module.  A config that wants them imports this module, or uses the
-- "XF86AudioPlay" spelling with "XMonad.Util.EZConfig", which resolves
-- through the shared table in "XMonad.River.Keysym.Table".
--
-- The values come from xkbcommon-keysyms.h, which reuses X11's numbering
-- wholesale, so @xK_XF86AudioPlay@ is 0x1008ff14 here and under X11 alike.
module XMonad.River.Keysym.XF86 (
%%NAMES%%
  ) where

import XMonad.River.Types (KeySym)

'''
xf86_names_block = []
for i in range(0, len(vals_xf86), 6):
    chunk = ", ".join(n for n, _ in vals_xf86[i:i + 6])
    xf86_names_block.append("  " + chunk + ("," if i + 6 < len(vals_xf86) else ""))
xf86_header = xf86_header.replace("%%NAMES%%", "\n".join(xf86_names_block))
xf86_lines = [xf86_header]
for i in range(0, len(vals_xf86), 8):
    chunk = ", ".join(n for n, _ in vals_xf86[i:i + 8])
    prefix = "" if i == 0 else "  "
    suffix = " :: KeySym" if i + 8 >= len(vals_xf86) else ","
    xf86_lines.append(prefix + chunk + suffix)
xf86_lines.append("")
xf86_lines += [f"{n} = {v}" for n, v in vals_xf86]
open(os.path.join(os.path.dirname(sys.argv[3]), "Keysym", "XF86.hs"), "w").write(
    "\n".join(xf86_lines) + "\n")

tbl = ['''-- | Keysym name lookup tables.
--
-- GENERATED by util/gen-keysyms.sh -- do not edit.
--
-- Separate from "XMonad.River.Keysym" so that "XMonad.Core" can re-export the
-- keysyms -- which exist on both backends -- without also exporting these,
-- which do not.  Anything river-specific is reachable only through
-- "XMonad.River".
module XMonad.River.Keysym.Table (keysymTable, reverseKeysymTable) where

import qualified Data.Map.Strict as M

import XMonad.River.Types (KeySym)

-- | Every keysym, keyed by the name X11 gives it.
keysymTable :: M.Map String KeySym
keysymTable = M.fromList''']
for i, (n, v) in enumerate(vals):
    tbl.append(("  [ " if i == 0 else "  , ") + f'("{n[3:]}", {v})')
tbl.append("  ]")
tbl.append("")
tbl.append("-- | The inverse of 'keysymTable'.")
tbl.append("reverseKeysymTable :: M.Map KeySym String")
tbl.append("reverseKeysymTable = M.fromList [ (v, k) | (k, v) <- M.toList keysymTable ]")
import os
open(os.path.join(os.path.dirname(sys.argv[3]), "Keysym", "Table.hs"), "w").write("\n".join(tbl) + "\n")
print(f"gen-keysyms: wrote {len(vals_x11)} X11 + {len(vals_xf86)} XF86 keysyms")
PY
