-- | The XF86 keysyms, with X11's values.
--
-- GENERATED by util/gen-keysyms.sh -- do not edit.
--
-- The Haskell X11 package does not export these, so they are not part of
-- xmonad's upstream-shaped API surface; "XMonad.Core" does not re-export
-- this module.  A config that wants them imports this module, or uses the
-- "XF86AudioPlay" spelling with "XMonad.Util.EZConfig", which resolves
-- through the shared table in "XMonad.River.Keysym.Table".
--
-- The values come from xkbcommon-keysyms.h, which reuses X11's numbering
-- wholesale, so @xK_XF86AudioPlay@ is 0x1008ff14 here and under X11 alike.
module XMonad.River.Keysym.XF86 (
  xK_XF8610ChannelsDown, xK_XF8610ChannelsUp, xK_XF863DMode, xK_XF86Accessibility, xK_XF86AddFavorite, xK_XF86Addressbook,
  xK_XF86ALSToggle, xK_XF86ApplicationLeft, xK_XF86ApplicationRight, xK_XF86AppSelect, xK_XF86AspectRatio, xK_XF86Assistant,
  xK_XF86AttendantOff, xK_XF86AttendantOn, xK_XF86AttendantToggle, xK_XF86Audio, xK_XF86AudioBassBoost, xK_XF86AudioChannelMode,
  xK_XF86AudioCycleTrack, xK_XF86AudioDesc, xK_XF86AudioForward, xK_XF86AudioLowerVolume, xK_XF86AudioMedia, xK_XF86AudioMicMute,
  xK_XF86AudioMute, xK_XF86AudioNext, xK_XF86AudioPause, xK_XF86AudioPlay, xK_XF86AudioPreset, xK_XF86AudioPrev,
  xK_XF86AudioRaiseVolume, xK_XF86AudioRandomPlay, xK_XF86AudioRecord, xK_XF86AudioRepeat, xK_XF86AudioRewind, xK_XF86AudioStop,
  xK_XF86AutopilotEngageToggle, xK_XF86Away, xK_XF86Back, xK_XF86BackForward, xK_XF86Battery, xK_XF86Blue,
  xK_XF86Bluetooth, xK_XF86Book, xK_XF86Break, xK_XF86BrightnessAdjust, xK_XF86BrightnessAuto, xK_XF86BrightnessMax,
  xK_XF86BrightnessMin, xK_XF86Buttonconfig, xK_XF86Calculater, xK_XF86Calculator, xK_XF86Calendar, xK_XF86CameraAccessDisable,
  xK_XF86CameraAccessEnable, xK_XF86CameraAccessToggle, xK_XF86CameraDown, xK_XF86CameraFocus, xK_XF86CameraLeft, xK_XF86CameraRight,
  xK_XF86CameraUp, xK_XF86CameraZoomIn, xK_XF86CameraZoomOut, xK_XF86CD, xK_XF86ChannelDown, xK_XF86ChannelUp,
  xK_XF86Clear, xK_XF86ClearGrab, xK_XF86ClearvuSonar, xK_XF86Close, xK_XF86Community, xK_XF86ContextMenu,
  xK_XF86ContrastAdjust, xK_XF86ControlPanel, xK_XF86Copy, xK_XF86Cut, xK_XF86CycleAngle, xK_XF86Data,
  xK_XF86Database, xK_XF86Dictate, xK_XF86Display, xK_XF86DisplayOff, xK_XF86DisplayToggle, xK_XF86Documents,
  xK_XF86DoNotDisturb, xK_XF86DOS, xK_XF86DualRangeRadar, xK_XF86DVD, xK_XF86Editor, xK_XF86Eject,
  xK_XF86EmojiPicker, xK_XF86Excel, xK_XF86Exit, xK_XF86Explorer, xK_XF86FastReverse, xK_XF86Favorites,
  xK_XF86Finance, xK_XF86FishingChart, xK_XF86Fn, xK_XF86Fn_1, xK_XF86Fn_2, xK_XF86Fn_B,
  xK_XF86Fn_D, xK_XF86Fn_E, xK_XF86Fn_Esc, xK_XF86Fn_F, xK_XF86Fn_F1, xK_XF86Fn_F10,
  xK_XF86Fn_F11, xK_XF86Fn_F12, xK_XF86Fn_F2, xK_XF86Fn_F3, xK_XF86Fn_F4, xK_XF86Fn_F5,
  xK_XF86Fn_F6, xK_XF86Fn_F7, xK_XF86Fn_F8, xK_XF86Fn_F9, xK_XF86FnRightShift, xK_XF86Fn_S,
  xK_XF86Forward, xK_XF86FrameBack, xK_XF86FrameForward, xK_XF86FullScreen, xK_XF86Game, xK_XF86Go,
  xK_XF86GoTo, xK_XF86GraphicsEditor, xK_XF86Green, xK_XF86HangupPhone, xK_XF86Hibernate, xK_XF86History,
  xK_XF86HomePage, xK_XF86HotLinks, xK_XF86Images, xK_XF86Info, xK_XF86iTouch, xK_XF86Journal,
  xK_XF86KbdBrightnessDown, xK_XF86KbdBrightnessUp, xK_XF86KbdInputAssistAccept, xK_XF86KbdInputAssistCancel, xK_XF86KbdInputAssistNext, xK_XF86KbdInputAssistNextgroup,
  xK_XF86KbdInputAssistPrev, xK_XF86KbdInputAssistPrevgroup, xK_XF86KbdLcdMenu1, xK_XF86KbdLcdMenu2, xK_XF86KbdLcdMenu3, xK_XF86KbdLcdMenu4,
  xK_XF86KbdLcdMenu5, xK_XF86KbdLightOnOff, xK_XF86Keyboard, xK_XF86Launch0, xK_XF86Launch1, xK_XF86Launch2,
  xK_XF86Launch3, xK_XF86Launch4, xK_XF86Launch5, xK_XF86Launch6, xK_XF86Launch7, xK_XF86Launch8,
  xK_XF86Launch9, xK_XF86LaunchA, xK_XF86LaunchB, xK_XF86LaunchC, xK_XF86LaunchD, xK_XF86LaunchE,
  xK_XF86LaunchF, xK_XF86LeftDown, xK_XF86LeftUp, xK_XF86LightBulb, xK_XF86LightsToggle, xK_XF86LinkPhone,
  xK_XF86LogGrabInfo, xK_XF86LogOff, xK_XF86LogWindowTree, xK_XF86Macro1, xK_XF86Macro10, xK_XF86Macro11,
  xK_XF86Macro12, xK_XF86Macro13, xK_XF86Macro14, xK_XF86Macro15, xK_XF86Macro16, xK_XF86Macro17,
  xK_XF86Macro18, xK_XF86Macro19, xK_XF86Macro2, xK_XF86Macro20, xK_XF86Macro21, xK_XF86Macro22,
  xK_XF86Macro23, xK_XF86Macro24, xK_XF86Macro25, xK_XF86Macro26, xK_XF86Macro27, xK_XF86Macro28,
  xK_XF86Macro29, xK_XF86Macro3, xK_XF86Macro30, xK_XF86Macro4, xK_XF86Macro5, xK_XF86Macro6,
  xK_XF86Macro7, xK_XF86Macro8, xK_XF86Macro9, xK_XF86MacroPreset1, xK_XF86MacroPreset2, xK_XF86MacroPreset3,
  xK_XF86MacroPresetCycle, xK_XF86MacroRecordStart, xK_XF86MacroRecordStop, xK_XF86Mail, xK_XF86MailForward, xK_XF86Market,
  xK_XF86MarkWaypoint, xK_XF86MediaLanguageMenu, xK_XF86MediaPlayer, xK_XF86MediaPlayPause, xK_XF86MediaPlaySlow, xK_XF86MediaRepeat,
  xK_XF86MediaSelectAuxiliary, xK_XF86MediaSelectCable, xK_XF86MediaSelectCD, xK_XF86MediaSelectDVD, xK_XF86MediaSelectHome, xK_XF86MediaSelectPC,
  xK_XF86MediaSelectProgramGuide, xK_XF86MediaSelectRadio, xK_XF86MediaSelectSatellite, xK_XF86MediaSelectTape, xK_XF86MediaSelectTeletext, xK_XF86MediaSelectTuner,
  xK_XF86MediaSelectTV, xK_XF86MediaSelectVCR, xK_XF86MediaSelectVCRPlus, xK_XF86MediaTitleMenu, xK_XF86MediaTopMenu, xK_XF86Meeting,
  xK_XF86Memo, xK_XF86MenuKB, xK_XF86MenuPB, xK_XF86Messenger, xK_XF86ModeLock, xK_XF86MonBrightnessAuto,
  xK_XF86MonBrightnessCycle, xK_XF86MonBrightnessDown, xK_XF86MonBrightnessUp, xK_XF86Music, xK_XF86MyComputer, xK_XF86MySites,
  xK_XF86NavChart, xK_XF86NavInfo, xK_XF86New, xK_XF86News, xK_XF86NextElement, xK_XF86NextFavorite,
  xK_XF86Next_VMode, xK_XF86NotificationCenter, xK_XF86NumberEntryMode, xK_XF86Numeric0, xK_XF86Numeric1, xK_XF86Numeric11,
  xK_XF86Numeric12, xK_XF86Numeric2, xK_XF86Numeric3, xK_XF86Numeric4, xK_XF86Numeric5, xK_XF86Numeric6,
  xK_XF86Numeric7, xK_XF86Numeric8, xK_XF86Numeric9, xK_XF86NumericA, xK_XF86NumericB, xK_XF86NumericC,
  xK_XF86NumericD, xK_XF86NumericPound, xK_XF86NumericStar, xK_XF86OfficeHome, xK_XF86OK, xK_XF86OnScreenKeyboard,
  xK_XF86Open, xK_XF86OpenURL, xK_XF86Option, xK_XF86Paste, xK_XF86PauseRecord, xK_XF86PerformanceMode,
  xK_XF86Phone, xK_XF86PickupPhone, xK_XF86Pictures, xK_XF86PowerDown, xK_XF86PowerOff, xK_XF86Presentation,
  xK_XF86PreviousElement, xK_XF86Prev_VMode, xK_XF86PrivacyScreenToggle, xK_XF86Q, xK_XF86RadarOverlay, xK_XF86Red,
  xK_XF86Refresh, xK_XF86RefreshRateToggle, xK_XF86Reload, xK_XF86Reply, xK_XF86RFKill, xK_XF86RightDown,
  xK_XF86RightUp, xK_XF86RockerDown, xK_XF86RockerEnter, xK_XF86RockerUp, xK_XF86RootMenu, xK_XF86RotateWindows,
  xK_XF86RotationKB, xK_XF86RotationLockToggle, xK_XF86RotationPB, xK_XF86Save, xK_XF86Screensaver, xK_XF86ScreenSaver,
  xK_XF86ScrollClick, xK_XF86ScrollDown, xK_XF86ScrollUp, xK_XF86Search, xK_XF86Select, xK_XF86SelectiveScreenshot,
  xK_XF86Send, xK_XF86Shop, xK_XF86SidevuSonar, xK_XF86SingleRangeRadar, xK_XF86Sleep, xK_XF86SlowReverse,
  xK_XF86Sos, xK_XF86Spell, xK_XF86SpellCheck, xK_XF86SplitScreen, xK_XF86Sport, xK_XF86Standby,
  xK_XF86Start, xK_XF86Stop, xK_XF86StopRecord, xK_XF86Subtitle, xK_XF86Support, xK_XF86Suspend,
  xK_XF86Switch_VT_1, xK_XF86Switch_VT_10, xK_XF86Switch_VT_11, xK_XF86Switch_VT_12, xK_XF86Switch_VT_2, xK_XF86Switch_VT_3,
  xK_XF86Switch_VT_4, xK_XF86Switch_VT_5, xK_XF86Switch_VT_6, xK_XF86Switch_VT_7, xK_XF86Switch_VT_8, xK_XF86Switch_VT_9,
  xK_XF86Taskmanager, xK_XF86TaskPane, xK_XF86Terminal, xK_XF86Time, xK_XF86ToDoList, xK_XF86Tools,
  xK_XF86TopMenu, xK_XF86TouchpadOff, xK_XF86TouchpadOn, xK_XF86TouchpadToggle, xK_XF86TraditionalSonar, xK_XF86Travel,
  xK_XF86Ungrab, xK_XF86Unmute, xK_XF86User1KB, xK_XF86User2KB, xK_XF86UserPB, xK_XF86UWB,
  xK_XF86VendorHome, xK_XF86VendorLogo, xK_XF86Video, xK_XF86VideoPhone, xK_XF86View, xK_XF86VOD,
  xK_XF86VoiceCommand, xK_XF86Voicemail, xK_XF86WakeUp, xK_XF86WebCam, xK_XF86WheelButton, xK_XF86WLAN,
  xK_XF86Word, xK_XF86WPSButton, xK_XF86WWAN, xK_XF86WWW, xK_XF86Xfer, xK_XF86Yellow,
  xK_XF86ZoomIn, xK_XF86ZoomOut, xK_XF86ZoomReset
  ) where

import XMonad.River.Types (KeySym)


xK_XF8610ChannelsDown, xK_XF8610ChannelsUp, xK_XF863DMode, xK_XF86Accessibility, xK_XF86AddFavorite, xK_XF86Addressbook, xK_XF86ALSToggle, xK_XF86ApplicationLeft,
  xK_XF86ApplicationRight, xK_XF86AppSelect, xK_XF86AspectRatio, xK_XF86Assistant, xK_XF86AttendantOff, xK_XF86AttendantOn, xK_XF86AttendantToggle, xK_XF86Audio,
  xK_XF86AudioBassBoost, xK_XF86AudioChannelMode, xK_XF86AudioCycleTrack, xK_XF86AudioDesc, xK_XF86AudioForward, xK_XF86AudioLowerVolume, xK_XF86AudioMedia, xK_XF86AudioMicMute,
  xK_XF86AudioMute, xK_XF86AudioNext, xK_XF86AudioPause, xK_XF86AudioPlay, xK_XF86AudioPreset, xK_XF86AudioPrev, xK_XF86AudioRaiseVolume, xK_XF86AudioRandomPlay,
  xK_XF86AudioRecord, xK_XF86AudioRepeat, xK_XF86AudioRewind, xK_XF86AudioStop, xK_XF86AutopilotEngageToggle, xK_XF86Away, xK_XF86Back, xK_XF86BackForward,
  xK_XF86Battery, xK_XF86Blue, xK_XF86Bluetooth, xK_XF86Book, xK_XF86Break, xK_XF86BrightnessAdjust, xK_XF86BrightnessAuto, xK_XF86BrightnessMax,
  xK_XF86BrightnessMin, xK_XF86Buttonconfig, xK_XF86Calculater, xK_XF86Calculator, xK_XF86Calendar, xK_XF86CameraAccessDisable, xK_XF86CameraAccessEnable, xK_XF86CameraAccessToggle,
  xK_XF86CameraDown, xK_XF86CameraFocus, xK_XF86CameraLeft, xK_XF86CameraRight, xK_XF86CameraUp, xK_XF86CameraZoomIn, xK_XF86CameraZoomOut, xK_XF86CD,
  xK_XF86ChannelDown, xK_XF86ChannelUp, xK_XF86Clear, xK_XF86ClearGrab, xK_XF86ClearvuSonar, xK_XF86Close, xK_XF86Community, xK_XF86ContextMenu,
  xK_XF86ContrastAdjust, xK_XF86ControlPanel, xK_XF86Copy, xK_XF86Cut, xK_XF86CycleAngle, xK_XF86Data, xK_XF86Database, xK_XF86Dictate,
  xK_XF86Display, xK_XF86DisplayOff, xK_XF86DisplayToggle, xK_XF86Documents, xK_XF86DoNotDisturb, xK_XF86DOS, xK_XF86DualRangeRadar, xK_XF86DVD,
  xK_XF86Editor, xK_XF86Eject, xK_XF86EmojiPicker, xK_XF86Excel, xK_XF86Exit, xK_XF86Explorer, xK_XF86FastReverse, xK_XF86Favorites,
  xK_XF86Finance, xK_XF86FishingChart, xK_XF86Fn, xK_XF86Fn_1, xK_XF86Fn_2, xK_XF86Fn_B, xK_XF86Fn_D, xK_XF86Fn_E,
  xK_XF86Fn_Esc, xK_XF86Fn_F, xK_XF86Fn_F1, xK_XF86Fn_F10, xK_XF86Fn_F11, xK_XF86Fn_F12, xK_XF86Fn_F2, xK_XF86Fn_F3,
  xK_XF86Fn_F4, xK_XF86Fn_F5, xK_XF86Fn_F6, xK_XF86Fn_F7, xK_XF86Fn_F8, xK_XF86Fn_F9, xK_XF86FnRightShift, xK_XF86Fn_S,
  xK_XF86Forward, xK_XF86FrameBack, xK_XF86FrameForward, xK_XF86FullScreen, xK_XF86Game, xK_XF86Go, xK_XF86GoTo, xK_XF86GraphicsEditor,
  xK_XF86Green, xK_XF86HangupPhone, xK_XF86Hibernate, xK_XF86History, xK_XF86HomePage, xK_XF86HotLinks, xK_XF86Images, xK_XF86Info,
  xK_XF86iTouch, xK_XF86Journal, xK_XF86KbdBrightnessDown, xK_XF86KbdBrightnessUp, xK_XF86KbdInputAssistAccept, xK_XF86KbdInputAssistCancel, xK_XF86KbdInputAssistNext, xK_XF86KbdInputAssistNextgroup,
  xK_XF86KbdInputAssistPrev, xK_XF86KbdInputAssistPrevgroup, xK_XF86KbdLcdMenu1, xK_XF86KbdLcdMenu2, xK_XF86KbdLcdMenu3, xK_XF86KbdLcdMenu4, xK_XF86KbdLcdMenu5, xK_XF86KbdLightOnOff,
  xK_XF86Keyboard, xK_XF86Launch0, xK_XF86Launch1, xK_XF86Launch2, xK_XF86Launch3, xK_XF86Launch4, xK_XF86Launch5, xK_XF86Launch6,
  xK_XF86Launch7, xK_XF86Launch8, xK_XF86Launch9, xK_XF86LaunchA, xK_XF86LaunchB, xK_XF86LaunchC, xK_XF86LaunchD, xK_XF86LaunchE,
  xK_XF86LaunchF, xK_XF86LeftDown, xK_XF86LeftUp, xK_XF86LightBulb, xK_XF86LightsToggle, xK_XF86LinkPhone, xK_XF86LogGrabInfo, xK_XF86LogOff,
  xK_XF86LogWindowTree, xK_XF86Macro1, xK_XF86Macro10, xK_XF86Macro11, xK_XF86Macro12, xK_XF86Macro13, xK_XF86Macro14, xK_XF86Macro15,
  xK_XF86Macro16, xK_XF86Macro17, xK_XF86Macro18, xK_XF86Macro19, xK_XF86Macro2, xK_XF86Macro20, xK_XF86Macro21, xK_XF86Macro22,
  xK_XF86Macro23, xK_XF86Macro24, xK_XF86Macro25, xK_XF86Macro26, xK_XF86Macro27, xK_XF86Macro28, xK_XF86Macro29, xK_XF86Macro3,
  xK_XF86Macro30, xK_XF86Macro4, xK_XF86Macro5, xK_XF86Macro6, xK_XF86Macro7, xK_XF86Macro8, xK_XF86Macro9, xK_XF86MacroPreset1,
  xK_XF86MacroPreset2, xK_XF86MacroPreset3, xK_XF86MacroPresetCycle, xK_XF86MacroRecordStart, xK_XF86MacroRecordStop, xK_XF86Mail, xK_XF86MailForward, xK_XF86Market,
  xK_XF86MarkWaypoint, xK_XF86MediaLanguageMenu, xK_XF86MediaPlayer, xK_XF86MediaPlayPause, xK_XF86MediaPlaySlow, xK_XF86MediaRepeat, xK_XF86MediaSelectAuxiliary, xK_XF86MediaSelectCable,
  xK_XF86MediaSelectCD, xK_XF86MediaSelectDVD, xK_XF86MediaSelectHome, xK_XF86MediaSelectPC, xK_XF86MediaSelectProgramGuide, xK_XF86MediaSelectRadio, xK_XF86MediaSelectSatellite, xK_XF86MediaSelectTape,
  xK_XF86MediaSelectTeletext, xK_XF86MediaSelectTuner, xK_XF86MediaSelectTV, xK_XF86MediaSelectVCR, xK_XF86MediaSelectVCRPlus, xK_XF86MediaTitleMenu, xK_XF86MediaTopMenu, xK_XF86Meeting,
  xK_XF86Memo, xK_XF86MenuKB, xK_XF86MenuPB, xK_XF86Messenger, xK_XF86ModeLock, xK_XF86MonBrightnessAuto, xK_XF86MonBrightnessCycle, xK_XF86MonBrightnessDown,
  xK_XF86MonBrightnessUp, xK_XF86Music, xK_XF86MyComputer, xK_XF86MySites, xK_XF86NavChart, xK_XF86NavInfo, xK_XF86New, xK_XF86News,
  xK_XF86NextElement, xK_XF86NextFavorite, xK_XF86Next_VMode, xK_XF86NotificationCenter, xK_XF86NumberEntryMode, xK_XF86Numeric0, xK_XF86Numeric1, xK_XF86Numeric11,
  xK_XF86Numeric12, xK_XF86Numeric2, xK_XF86Numeric3, xK_XF86Numeric4, xK_XF86Numeric5, xK_XF86Numeric6, xK_XF86Numeric7, xK_XF86Numeric8,
  xK_XF86Numeric9, xK_XF86NumericA, xK_XF86NumericB, xK_XF86NumericC, xK_XF86NumericD, xK_XF86NumericPound, xK_XF86NumericStar, xK_XF86OfficeHome,
  xK_XF86OK, xK_XF86OnScreenKeyboard, xK_XF86Open, xK_XF86OpenURL, xK_XF86Option, xK_XF86Paste, xK_XF86PauseRecord, xK_XF86PerformanceMode,
  xK_XF86Phone, xK_XF86PickupPhone, xK_XF86Pictures, xK_XF86PowerDown, xK_XF86PowerOff, xK_XF86Presentation, xK_XF86PreviousElement, xK_XF86Prev_VMode,
  xK_XF86PrivacyScreenToggle, xK_XF86Q, xK_XF86RadarOverlay, xK_XF86Red, xK_XF86Refresh, xK_XF86RefreshRateToggle, xK_XF86Reload, xK_XF86Reply,
  xK_XF86RFKill, xK_XF86RightDown, xK_XF86RightUp, xK_XF86RockerDown, xK_XF86RockerEnter, xK_XF86RockerUp, xK_XF86RootMenu, xK_XF86RotateWindows,
  xK_XF86RotationKB, xK_XF86RotationLockToggle, xK_XF86RotationPB, xK_XF86Save, xK_XF86Screensaver, xK_XF86ScreenSaver, xK_XF86ScrollClick, xK_XF86ScrollDown,
  xK_XF86ScrollUp, xK_XF86Search, xK_XF86Select, xK_XF86SelectiveScreenshot, xK_XF86Send, xK_XF86Shop, xK_XF86SidevuSonar, xK_XF86SingleRangeRadar,
  xK_XF86Sleep, xK_XF86SlowReverse, xK_XF86Sos, xK_XF86Spell, xK_XF86SpellCheck, xK_XF86SplitScreen, xK_XF86Sport, xK_XF86Standby,
  xK_XF86Start, xK_XF86Stop, xK_XF86StopRecord, xK_XF86Subtitle, xK_XF86Support, xK_XF86Suspend, xK_XF86Switch_VT_1, xK_XF86Switch_VT_10,
  xK_XF86Switch_VT_11, xK_XF86Switch_VT_12, xK_XF86Switch_VT_2, xK_XF86Switch_VT_3, xK_XF86Switch_VT_4, xK_XF86Switch_VT_5, xK_XF86Switch_VT_6, xK_XF86Switch_VT_7,
  xK_XF86Switch_VT_8, xK_XF86Switch_VT_9, xK_XF86Taskmanager, xK_XF86TaskPane, xK_XF86Terminal, xK_XF86Time, xK_XF86ToDoList, xK_XF86Tools,
  xK_XF86TopMenu, xK_XF86TouchpadOff, xK_XF86TouchpadOn, xK_XF86TouchpadToggle, xK_XF86TraditionalSonar, xK_XF86Travel, xK_XF86Ungrab, xK_XF86Unmute,
  xK_XF86User1KB, xK_XF86User2KB, xK_XF86UserPB, xK_XF86UWB, xK_XF86VendorHome, xK_XF86VendorLogo, xK_XF86Video, xK_XF86VideoPhone,
  xK_XF86View, xK_XF86VOD, xK_XF86VoiceCommand, xK_XF86Voicemail, xK_XF86WakeUp, xK_XF86WebCam, xK_XF86WheelButton, xK_XF86WLAN,
  xK_XF86Word, xK_XF86WPSButton, xK_XF86WWAN, xK_XF86WWW, xK_XF86Xfer, xK_XF86Yellow, xK_XF86ZoomIn, xK_XF86ZoomOut,
  xK_XF86ZoomReset :: KeySym

xK_XF8610ChannelsDown = 268964281
xK_XF8610ChannelsUp = 268964280
xK_XF863DMode = 268964463
xK_XF86Accessibility = 268964430
xK_XF86AddFavorite = 269025081
xK_XF86Addressbook = 268964269
xK_XF86ALSToggle = 268964400
xK_XF86ApplicationLeft = 269025104
xK_XF86ApplicationRight = 269025105
xK_XF86AppSelect = 268964420
xK_XF86AspectRatio = 268964215
xK_XF86Assistant = 268964423
xK_XF86AttendantOff = 268964380
xK_XF86AttendantOn = 268964379
xK_XF86AttendantToggle = 268964381
xK_XF86Audio = 268964232
xK_XF86AudioBassBoost = 268964049
xK_XF86AudioChannelMode = 268964213
xK_XF86AudioCycleTrack = 269025179
xK_XF86AudioDesc = 268964462
xK_XF86AudioForward = 269025175
xK_XF86AudioLowerVolume = 269025041
xK_XF86AudioMedia = 269025074
xK_XF86AudioMicMute = 269025202
xK_XF86AudioMute = 269025042
xK_XF86AudioNext = 269025047
xK_XF86AudioPause = 269025073
xK_XF86AudioPlay = 269025044
xK_XF86AudioPreset = 269025206
xK_XF86AudioPrev = 269025046
xK_XF86AudioRaiseVolume = 269025043
xK_XF86AudioRandomPlay = 269025177
xK_XF86AudioRecord = 269025052
xK_XF86AudioRepeat = 269025176
xK_XF86AudioRewind = 269025086
xK_XF86AudioStop = 269025045
xK_XF86AutopilotEngageToggle = 268964477
xK_XF86Away = 269025165
xK_XF86Back = 269025062
xK_XF86BackForward = 269025087
xK_XF86Battery = 269025171
xK_XF86Blue = 269025190
xK_XF86Bluetooth = 269025172
xK_XF86Book = 269025106
xK_XF86Break = 268964251
xK_XF86BrightnessAdjust = 269025083
xK_XF86BrightnessAuto = 268964084
xK_XF86BrightnessMax = 268964433
xK_XF86BrightnessMin = 268964432
xK_XF86Buttonconfig = 268964416
xK_XF86Calculater = 269025108
xK_XF86Calculator = 269025053
xK_XF86Calendar = 269025056
xK_XF86CameraAccessDisable = 268964428
xK_XF86CameraAccessEnable = 268964427
xK_XF86CameraAccessToggle = 268964429
xK_XF86CameraDown = 268964376
xK_XF86CameraFocus = 268964368
xK_XF86CameraLeft = 268964377
xK_XF86CameraRight = 268964378
xK_XF86CameraUp = 268964375
xK_XF86CameraZoomIn = 268964373
xK_XF86CameraZoomOut = 268964374
xK_XF86CD = 269025107
xK_XF86ChannelDown = 268964243
xK_XF86ChannelUp = 268964242
xK_XF86Clear = 269025109
xK_XF86ClearGrab = 269024801
xK_XF86ClearvuSonar = 268964486
xK_XF86Close = 269025110
xK_XF86Community = 269025085
xK_XF86ContextMenu = 268964278
xK_XF86ContrastAdjust = 269025058
xK_XF86ControlPanel = 268964419
xK_XF86Copy = 269025111
xK_XF86Cut = 269025112
xK_XF86CycleAngle = 269025180
xK_XF86Data = 268964471
xK_XF86Database = 268964266
xK_XF86Dictate = 268964426
xK_XF86Display = 269025113
xK_XF86DisplayOff = 268964085
xK_XF86DisplayToggle = 268964271
xK_XF86Documents = 269025115
xK_XF86DoNotDisturb = 268964431
xK_XF86DOS = 269025114
xK_XF86DualRangeRadar = 268964483
xK_XF86DVD = 268964229
xK_XF86Editor = 268964262
xK_XF86Eject = 269025068
xK_XF86EmojiPicker = 268964425
xK_XF86Excel = 269025116
xK_XF86Exit = 268964014
xK_XF86Explorer = 269025117
xK_XF86FastReverse = 268964469
xK_XF86Favorites = 269025072
xK_XF86Finance = 269025084
xK_XF86FishingChart = 268964481
xK_XF86Fn = 268964304
xK_XF86Fn_1 = 268964318
xK_XF86Fn_2 = 268964319
xK_XF86Fn_B = 268964324
xK_XF86Fn_D = 268964320
xK_XF86Fn_E = 268964321
xK_XF86Fn_Esc = 268964305
xK_XF86Fn_F = 268964322
xK_XF86Fn_F1 = 268964306
xK_XF86Fn_F10 = 268964315
xK_XF86Fn_F11 = 268964316
xK_XF86Fn_F12 = 268964317
xK_XF86Fn_F2 = 268964307
xK_XF86Fn_F3 = 268964308
xK_XF86Fn_F4 = 268964309
xK_XF86Fn_F5 = 268964310
xK_XF86Fn_F6 = 268964311
xK_XF86Fn_F7 = 268964312
xK_XF86Fn_F8 = 268964313
xK_XF86Fn_F9 = 268964314
xK_XF86FnRightShift = 268964325
xK_XF86Fn_S = 268964323
xK_XF86Forward = 269025063
xK_XF86FrameBack = 269025181
xK_XF86FrameForward = 269025182
xK_XF86FullScreen = 269025208
xK_XF86Game = 269025118
xK_XF86Go = 269025119
xK_XF86GoTo = 268964194
xK_XF86GraphicsEditor = 268964264
xK_XF86Green = 269025188
xK_XF86HangupPhone = 268964286
xK_XF86Hibernate = 269025192
xK_XF86History = 269025079
xK_XF86HomePage = 269025048
xK_XF86HotLinks = 269025082
xK_XF86Images = 268964282
xK_XF86Info = 268964198
xK_XF86iTouch = 269025120
xK_XF86Journal = 268964418
xK_XF86KbdBrightnessDown = 269025030
xK_XF86KbdBrightnessUp = 269025029
xK_XF86KbdInputAssistAccept = 268964452
xK_XF86KbdInputAssistCancel = 268964453
xK_XF86KbdInputAssistNext = 268964449
xK_XF86KbdInputAssistNextgroup = 268964451
xK_XF86KbdInputAssistPrev = 268964448
xK_XF86KbdInputAssistPrevgroup = 268964450
xK_XF86KbdLcdMenu1 = 268964536
xK_XF86KbdLcdMenu2 = 268964537
xK_XF86KbdLcdMenu3 = 268964538
xK_XF86KbdLcdMenu4 = 268964539
xK_XF86KbdLcdMenu5 = 268964540
xK_XF86KbdLightOnOff = 269025028
xK_XF86Keyboard = 269025203
xK_XF86Launch0 = 269025088
xK_XF86Launch1 = 269025089
xK_XF86Launch2 = 269025090
xK_XF86Launch3 = 269025091
xK_XF86Launch4 = 269025092
xK_XF86Launch5 = 269025093
xK_XF86Launch6 = 269025094
xK_XF86Launch7 = 269025095
xK_XF86Launch8 = 269025096
xK_XF86Launch9 = 269025097
xK_XF86LaunchA = 269025098
xK_XF86LaunchB = 269025099
xK_XF86LaunchC = 269025100
xK_XF86LaunchD = 269025101
xK_XF86LaunchE = 269025102
xK_XF86LaunchF = 269025103
xK_XF86LeftDown = 268964457
xK_XF86LeftUp = 268964456
xK_XF86LightBulb = 269025077
xK_XF86LightsToggle = 268964382
xK_XF86LinkPhone = 268964287
xK_XF86LogGrabInfo = 269024805
xK_XF86LogOff = 269025121
xK_XF86LogWindowTree = 269024804
xK_XF86Macro1 = 268964496
xK_XF86Macro10 = 268964505
xK_XF86Macro11 = 268964506
xK_XF86Macro12 = 268964507
xK_XF86Macro13 = 268964508
xK_XF86Macro14 = 268964509
xK_XF86Macro15 = 268964510
xK_XF86Macro16 = 268964511
xK_XF86Macro17 = 268964512
xK_XF86Macro18 = 268964513
xK_XF86Macro19 = 268964514
xK_XF86Macro2 = 268964497
xK_XF86Macro20 = 268964515
xK_XF86Macro21 = 268964516
xK_XF86Macro22 = 268964517
xK_XF86Macro23 = 268964518
xK_XF86Macro24 = 268964519
xK_XF86Macro25 = 268964520
xK_XF86Macro26 = 268964521
xK_XF86Macro27 = 268964522
xK_XF86Macro28 = 268964523
xK_XF86Macro29 = 268964524
xK_XF86Macro3 = 268964498
xK_XF86Macro30 = 268964525
xK_XF86Macro4 = 268964499
xK_XF86Macro5 = 268964500
xK_XF86Macro6 = 268964501
xK_XF86Macro7 = 268964502
xK_XF86Macro8 = 268964503
xK_XF86Macro9 = 268964504
xK_XF86MacroPreset1 = 268964531
xK_XF86MacroPreset2 = 268964532
xK_XF86MacroPreset3 = 268964533
xK_XF86MacroPresetCycle = 268964530
xK_XF86MacroRecordStart = 268964528
xK_XF86MacroRecordStop = 268964529
xK_XF86Mail = 269025049
xK_XF86MailForward = 269025168
xK_XF86Market = 269025122
xK_XF86MarkWaypoint = 268964478
xK_XF86MediaLanguageMenu = 268964208
xK_XF86MediaPlayer = 268964227
xK_XF86MediaPlayPause = 268964004
xK_XF86MediaPlaySlow = 268964249
xK_XF86MediaRepeat = 268964279
xK_XF86MediaSelectAuxiliary = 268964230
xK_XF86MediaSelectCable = 268964218
xK_XF86MediaSelectCD = 269025107
xK_XF86MediaSelectDVD = 268964229
xK_XF86MediaSelectHome = 268964206
xK_XF86MediaSelectPC = 268964216
xK_XF86MediaSelectProgramGuide = 268964202
xK_XF86MediaSelectRadio = 268964225
xK_XF86MediaSelectSatellite = 268964221
xK_XF86MediaSelectTape = 268964224
xK_XF86MediaSelectTeletext = 268964228
xK_XF86MediaSelectTuner = 268964226
xK_XF86MediaSelectTV = 268964217
xK_XF86MediaSelectVCR = 268964219
xK_XF86MediaSelectVCRPlus = 268964220
xK_XF86MediaTitleMenu = 268964209
xK_XF86MediaTopMenu = 268964459
xK_XF86Meeting = 269025123
xK_XF86Memo = 269025054
xK_XF86MenuKB = 269025125
xK_XF86MenuPB = 269025126
xK_XF86Messenger = 269025166
xK_XF86ModeLock = 269025025
xK_XF86MonBrightnessAuto = 268964084
xK_XF86MonBrightnessCycle = 269025031
xK_XF86MonBrightnessDown = 269025027
xK_XF86MonBrightnessUp = 269025026
xK_XF86Music = 269025170
xK_XF86MyComputer = 269025075
xK_XF86MySites = 269025127
xK_XF86NavChart = 268964480
xK_XF86NavInfo = 268964488
xK_XF86New = 269025128
xK_XF86News = 269025129
xK_XF86NextElement = 268964475
xK_XF86NextFavorite = 268964464
xK_XF86Next_VMode = 269024802
xK_XF86NotificationCenter = 268964284
xK_XF86NumberEntryMode = 268964253
xK_XF86Numeric0 = 268964352
xK_XF86Numeric1 = 268964353
xK_XF86Numeric11 = 268964460
xK_XF86Numeric12 = 268964461
xK_XF86Numeric2 = 268964354
xK_XF86Numeric3 = 268964355
xK_XF86Numeric4 = 268964356
xK_XF86Numeric5 = 268964357
xK_XF86Numeric6 = 268964358
xK_XF86Numeric7 = 268964359
xK_XF86Numeric8 = 268964360
xK_XF86Numeric9 = 268964361
xK_XF86NumericA = 268964364
xK_XF86NumericB = 268964365
xK_XF86NumericC = 268964366
xK_XF86NumericD = 268964367
xK_XF86NumericPound = 268964363
xK_XF86NumericStar = 268964362
xK_XF86OfficeHome = 269025130
xK_XF86OK = 268964192
xK_XF86OnScreenKeyboard = 268964472
xK_XF86Open = 269025131
xK_XF86OpenURL = 269025080
xK_XF86Option = 269025132
xK_XF86Paste = 269025133
xK_XF86PauseRecord = 268964466
xK_XF86PerformanceMode = 268964541
xK_XF86Phone = 269025134
xK_XF86PickupPhone = 268964285
xK_XF86Pictures = 269025169
xK_XF86PowerDown = 269025057
xK_XF86PowerOff = 269025066
xK_XF86Presentation = 268964265
xK_XF86PreviousElement = 268964476
xK_XF86Prev_VMode = 269024803
xK_XF86PrivacyScreenToggle = 268964473
xK_XF86Q = 269025136
xK_XF86RadarOverlay = 268964484
xK_XF86Red = 269025187
xK_XF86Refresh = 269025065
xK_XF86RefreshRateToggle = 268964402
xK_XF86Reload = 269025139
xK_XF86Reply = 269025138
xK_XF86RFKill = 269025205
xK_XF86RightDown = 268964455
xK_XF86RightUp = 268964454
xK_XF86RockerDown = 269025060
xK_XF86RockerEnter = 269025061
xK_XF86RockerUp = 269025059
xK_XF86RootMenu = 268964458
xK_XF86RotateWindows = 269025140
xK_XF86RotationKB = 269025142
xK_XF86RotationLockToggle = 269025207
xK_XF86RotationPB = 269025141
xK_XF86Save = 269025143
xK_XF86Screensaver = 268964421
xK_XF86ScreenSaver = 269025069
xK_XF86ScrollClick = 269025146
xK_XF86ScrollDown = 269025145
xK_XF86ScrollUp = 269025144
xK_XF86Search = 269025051
xK_XF86Select = 269025184
xK_XF86SelectiveScreenshot = 268964474
xK_XF86Send = 269025147
xK_XF86Shop = 269025078
xK_XF86SidevuSonar = 268964487
xK_XF86SingleRangeRadar = 268964482
xK_XF86Sleep = 269025071
xK_XF86SlowReverse = 268964470
xK_XF86Sos = 268964479
xK_XF86Spell = 269025148
xK_XF86SpellCheck = 268964272
xK_XF86SplitScreen = 269025149
xK_XF86Sport = 268964060
xK_XF86Standby = 269025040
xK_XF86Start = 269025050
xK_XF86Stop = 269025064
xK_XF86StopRecord = 268964465
xK_XF86Subtitle = 269025178
xK_XF86Support = 269025150
xK_XF86Suspend = 269025191
xK_XF86Switch_VT_1 = 269024769
xK_XF86Switch_VT_10 = 269024778
xK_XF86Switch_VT_11 = 269024779
xK_XF86Switch_VT_12 = 269024780
xK_XF86Switch_VT_2 = 269024770
xK_XF86Switch_VT_3 = 269024771
xK_XF86Switch_VT_4 = 269024772
xK_XF86Switch_VT_5 = 269024773
xK_XF86Switch_VT_6 = 269024774
xK_XF86Switch_VT_7 = 269024775
xK_XF86Switch_VT_8 = 269024776
xK_XF86Switch_VT_9 = 269024777
xK_XF86Taskmanager = 268964417
xK_XF86TaskPane = 269025151
xK_XF86Terminal = 269025152
xK_XF86Time = 269025183
xK_XF86ToDoList = 269025055
xK_XF86Tools = 269025153
xK_XF86TopMenu = 269025186
xK_XF86TouchpadOff = 269025201
xK_XF86TouchpadOn = 269025200
xK_XF86TouchpadToggle = 269025193
xK_XF86TraditionalSonar = 268964485
xK_XF86Travel = 269025154
xK_XF86Ungrab = 269024800
xK_XF86Unmute = 268964468
xK_XF86User1KB = 269025157
xK_XF86User2KB = 269025158
xK_XF86UserPB = 269025156
xK_XF86UWB = 269025174
xK_XF86VendorHome = 269025076
xK_XF86VendorLogo = 268964200
xK_XF86Video = 269025159
xK_XF86VideoPhone = 268964256
xK_XF86View = 269025185
xK_XF86VOD = 268964467
xK_XF86VoiceCommand = 268964422
xK_XF86Voicemail = 268964268
xK_XF86WakeUp = 269025067
xK_XF86WebCam = 269025167
xK_XF86WheelButton = 269025160
xK_XF86WLAN = 269025173
xK_XF86Word = 269025161
xK_XF86WPSButton = 268964369
xK_XF86WWAN = 269025204
xK_XF86WWW = 269025070
xK_XF86Xfer = 269025162
xK_XF86Yellow = 269025189
xK_XF86ZoomIn = 269025163
xK_XF86ZoomOut = 269025164
xK_XF86ZoomReset = 268964260
